---
- name: Create Subscribed Library
  community.vmware.vmware_content_library_manager:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}"
    password: "{{ nested_vcenter.password }}"
    validate_certs: False
    library_name: "{{ tkgs.content_library_name }}"
    library_type: subscribed
    subscription_url: "{{ tkgs.content_library_url }}"
    update_on_demand: True
    ssl_thumbprint: "{{ tkgs.content_library_thumbprint | default(omit) }}"
    datastore_name: "{{ tkgs.datastore_to_tag }}"
    state: present
  delegate_to: localhost