---
- name: Deploy VC and Hosts
  hosts: localhost
  gather_facts: False
  roles:
    - role: vsphere/vsphere-deploy-vc-and-hosts
    - role: vsphere/vsphere-datacenter
    - role: vsphere/vsphere-clusters
    - role: vsphere/vsphere-vswitch0-port-groups
    - role: vsphere/vsphere-local-datastores
    - role: vsphere/vsphere-enable-cluster-services
    - role: vsphere/vsphere-resource-pools
    - role: vsphere/vsphere-distributed-switches
      when: 'distributed_switches is defined'
    - role: vsphere/vsphere-distributed-port-groups
      when: 'distributed_switches is defined'

    # NSX-T Section
    - role: nsxt/nsxt-manager
      when: 'nsxt is defined'
    - role: nsxt/nsxt-ip-pools
      when: 'nsxt is defined'
    - role: nsxt/nsxt-uplink-profiles
      when: 'nsxt is defined'
    - role: nsxt/nsxt-transport-zones
      when: 'nsxt is defined'
    - role: nsxt/nsxt-transport-nodes
      when: 'nsxt is defined'
    - role: nsxt/nsxt-edge-clusters
      when: 'nsxt is defined'
    - role: nsxt/nsxt-switching-routing
      when: 'nsxt is defined'

    ### vSphere with Kubernetes Section
    - role: vsphere/vsphere-tag-datastore
      when: 'tkgs is defined'
    - role: vsphere/vsphere-content-library
      when: 'tkgs is defined'
    - role: vsphere-tanzu/tkgs-vyos-router
      when: 'tkgs is defined and tkgs.router is defined'
    - role: vsphere-tanzu/tkgs-ha-proxy
      when: 'tkgs is defined'
    - role: vsphere-tanzu/tkgs-enable-cluster
      when: 'tkgs is defined'
    