---
- name: Deploy HA Proxy
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}" 
    password: "{{ nested_vcenter.password }}" 
    validate_certs: no
    name: "tkgs-haproxy"
    datacenter: "{{ nested_vcenter.datacenter }}"
    cluster: "{{ tkgs.vsphere_cluster }}"
    datastore: "{{ tkgs.datastore_to_tag }}"
    disk_provisioning: "{{ disk_mode }}"
    networks:  
      Management: "{{ tkgs.haproxy.management_port_group }}"
      Workload: "{{ tkgs.haproxy.workload_port_group }}"
      Frontend: "{{ tkgs.haproxy.workload_port_group }}"
    ova: "{{ lookup('env', 'SOFTWARE_DIR') }}/vmware-haproxy-v0.1.8.ova" 
    allow_duplicates: no
    power_on: yes
    fail_on_spec_warnings: yes
    wait: yes
    wait_for_ip_address: yes
    inject_ovf_env: yes
    properties:
      appliance.root_pwd: "{{ tkgs.haproxy.root_pwd }}"
      network.nameservers: "{{ tkgs.haproxy.nameservers }} "
      network.management_ip: "{{ tkgs.haproxy.management_ip }}"
      network.management_gateway: "{{ tkgs.haproxy.management_gateway }}"
      network.workload_ip: "{{ tkgs.haproxy.workload_ip }}"
      network.workload_gateway: "{{ tkgs.haproxy.workload_gateway }}"
      loadbalance.service_ip_range: "{{ tkgs.haproxy.service_ip_range }}"
      loadbalance.haproxy_user: "{{ tkgs.haproxy.username }}"
      loadbalance.haproxy_pwd:  "{{ tkgs.haproxy.password }}"
      loadbalance.dataplane_port: "{{ tkgs.haproxy.management_port | default(omit) }}"