---
- name: Create uplink profile
  nsxt_uplink_profiles:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: False
    resource_type: UplinkHostSwitchProfile
    display_name: "{{ item.display_name }}"
    mtu: "{{ item.mtu | default(omit)}}"
    teaming: "{{ item.teaming }}"
    transport_vlan: "{{ item.transport_vlan }}"
    state: "present"
  with_items:
    - "{{ nsxt.uplink_profiles }}"  