---

- debug: msg="{{tkgs}}"

- name: Deploy VYoS
  community.vmware.vmware_deploy_ovf:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}" 
    password: "{{ nested_vcenter.password }}" 
    validate_certs: no
    name: "tkgs-vyos-router"
    datacenter: "{{ nested_vcenter.datacenter }}"
    cluster: "{{ tkgs.vsphere_cluster }}"
    datastore: "{{ tkgs.datastore_to_tag }}"
    disk_provisioning: "{{ disk_mode }}"
    networks:  
      public: "{{ tkgs.management_port_group }}"
      internal: "{{ tkgs.workload_port_group }}"
    ova: "{{ lookup('env', 'SOFTWARE_DIR') }}/vyos-1.1.8-amd64.ova" 
    allow_duplicates: no
    power_on: yes
    fail_on_spec_warnings: yes
    wait: yes
    wait_for_ip_address: yes
    inject_ovf_env: no

- name: Configure VyOS VM
  community.vmware.vmware_vm_shell:
    hostname: "{{ nested_vcenter.ip }}"
    username: "{{ nested_vcenter.username }}" 
    password: "{{ nested_vcenter.password }}" 
    datacenter: "{{ nested_vcenter.datacenter }}"
    validate_certs: false
    vm_id: "tkgs-vyos-router"
    vm_username: "vyos"
    vm_password: "vyos"
    vm_shell: /bin/vbash
    vm_shell_args: |-
      -c "source /opt/vyatta/etc/functions/script-template
      configure
      delete interfaces ethernet eth0 address dhcp
      set interfaces ethernet eth0 address '{{ tkgs.router.uplink_ip_cidr }}'
      set interfaces ethernet eth1 address '{{ tkgs.router.internal_gateway_cidr }}'
      set service ssh port '22'
      set protocols static route 0.0.0.0/0 next-hop {{ tkgs.router.uplink_next_hop }} distance '1'

      set nat source rule 100 outbound-interface 'eth0'
      set nat source rule 100 source address '{{ tkgs.router.internal_network_cidr }}'
      set nat source rule 100 translation address masquerade

      commit
      save"
    vm_shell_cwd: "/home/vyos"
  register: results