---
- name: Add edge cluster
  nsxt_edge_clusters:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: False
    display_name: "{{ item.edge_cluster_name }}"
    description: "{{ item.description | default(omit) }}"
    cluster_profile_bindings:
    - profile_name: nsx-default-edge-high-availability-profile
      resource_type: EdgeHighAvailabilityProfile
    members: "{{ item.edge_cluster_members }}"
    state: present
  with_items: "{{ nsxt.edge_clusters }}"
  retries: 12
  delay: 10
  until: "'rc' not in edge_cluster_result"
  register: edge_cluster_result

- name: List Edge Clusters
  nsxt_edge_clusters_facts:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: False
  register: edge_clusters

- debug: var=edge_cluster_result

- name: Wait 5 minutes for the edge clusters to be fully configured
  wait_for:
    timeout: 300
  when: edge_cluster_result.changed

- name: List Edge Clusters
  nsxt_edge_clusters_facts:
    hostname: "{{ nsxt.manager.hostname }}"
    username: "{{ nsxt.manager.username }}"
    password: "{{ nsxt.manager.password }}"
    validate_certs: False
  register: edge_clusters

- debug: var=edge_cluster_result